[2015-06-23 04:58:58] api.ERROR: exception 'Symfony\Component\Debug\Exception\ContextErrorException' with message 'Warning: mb_convert_encoding() expects at least 2 parameters, 1 given' in /Users/yuichi/dev/VOYAGE_GROUP/vg-1day-2015-6-23/yopida/web-server/app.php:33 Stack trace: #0 [internal function]: Symfony\Component\Debug\ErrorHandler->handleError(2, 'mb_convert_enco...', '/Users/yuichi/d...', 33, Array) #1 /Users/yuichi/dev/VOYAGE_GROUP/vg-1day-2015-6-23/yopida/web-server/app.php(33): mb_convert_encoding(NULL) #2 [internal function]: {closure}(Object(Symfony\Component\HttpFoundation\Request)) #3 /Users/yuichi/dev/VOYAGE_GROUP/vg-1day-2015-6-23/yopida/web-server/vendor/symfony/http-kernel/Symfony/Component/HttpKernel/HttpKernel.php(145): call_user_func_array(Object(Closure), Array) #4 /Users/yuichi/dev/VOYAGE_GROUP/vg-1day-2015-6-23/yopida/web-server/vendor/symfony/http-kernel/Symfony/Component/HttpKernel/HttpKernel.php(66): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /Users/yuichi/dev/VOYAGE_GROUP/vg-1day-2015-6-23/yopida/web-server/vendor/silex/silex/src/Silex/Application.php(547): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /Users/yuichi/dev/VOYAGE_GROUP/vg-1day-2015-6-23/yopida/web-server/vendor/silex/silex/src/Silex/Application.php(524): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #7 /Users/yuichi/dev/VOYAGE_GROUP/vg-1day-2015-6-23/yopida/web-server/web/index.php(12): Silex\Application->run() #8 {main} [] []
[2015-06-23 06:39:27] api.ERROR: exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 1 table vg_message has no column named count' in /Users/yuichi/dev/VOYAGE_GROUP/vg-1day-2015-6-23/yopida/web-server/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:77 Stack trace: #0 /Users/yuichi/dev/VOYAGE_GROUP/vg-1day-2015-6-23/yopida/web-server/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(77): PDO->prepare('INSERT INTO vg_...', Array) #1 /Users/yuichi/dev/VOYAGE_GROUP/vg-1day-2015-6-23/yopida/web-server/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(984): Doctrine\DBAL\Driver\PDOConnection->prepare('INSERT INTO vg_...') #2 /Users/yuichi/dev/VOYAGE_GROUP/vg-1day-2015-6-23/yopida/web-server/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(696): Doctrine\DBAL\Connection->executeUpdate('INSERT INTO vg_...', Array, Array) #3 /Users/yuichi/dev/VOYAGE_GROUP/vg-1day-2015-6-23/yopida/web-server/src/My1DayServer/Repository/MessageRepository.php(54): Doctrine\DBAL\Connection->insert('vg_message', Array) #4 /Users/yuichi/dev/VOYAGE_GROUP/vg-1day-2015-6-23/yopida/web-server/src/My1DayServer/Application.php(163): My1DayServer\Repository\MessageRepository->createMessage(Array) #5 /Users/yuichi/dev/VOYAGE_GROUP/vg-1day-2015-6-23/yopida/web-server/app.php(31): My1DayServer\Application->createMessage('', NULL, '/9j/4AAQSkZJRgA...', NULL) #6 [internal function]: {closure}(Object(Symfony\Component\HttpFoundation\Request)) #7 /Users/yuichi/dev/VOYAGE_GROUP/vg-1day-2015-6-23/yopida/web-server/vendor/symfony/http-kernel/Symfony/Component/HttpKernel/HttpKernel.php(145): call_user_func_array(Object(Closure), Array) #8 /Users/yuichi/dev/VOYAGE_GROUP/vg-1day-2015-6-23/yopida/web-server/vendor/symfony/http-kernel/Symfony/Component/HttpKernel/HttpKernel.php(66): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #9 /Users/yuichi/dev/VOYAGE_GROUP/vg-1day-2015-6-23/yopida/web-server/vendor/silex/silex/src/Silex/Application.php(547): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #10 /Users/yuichi/dev/VOYAGE_GROUP/vg-1day-2015-6-23/yopida/web-server/vendor/silex/silex/src/Silex/Application.php(524): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #11 /Users/yuichi/dev/VOYAGE_GROUP/vg-1day-2015-6-23/yopida/web-server/web/index.php(12): Silex\Application->run() #12 {main}  Next exception 'Doctrine\DBAL\Driver\PDOException' with message 'SQLSTATE[HY000]: General error: 1 table vg_message has no column named count' in /Users/yuichi/dev/VOYAGE_GROUP/vg-1day-2015-6-23/yopida/web-server/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:79 Stack trace: #0 /Users/yuichi/dev/VOYAGE_GROUP/vg-1day-2015-6-23/yopida/web-server/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(984): Doctrine\DBAL\Driver\PDOConnection->prepare('INSERT INTO vg_...') #1 /Users/yuichi/dev/VOYAGE_GROUP/vg-1day-2015-6-23/yopida/web-server/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(696): Doctrine\DBAL\Connection->executeUpdate('INSERT INTO vg_...', Array, Array) #2 /Users/yuichi/dev/VOYAGE_GROUP/vg-1day-2015-6-23/yopida/web-server/src/My1DayServer/Repository/MessageRepository.php(54): Doctrine\DBAL\Connection->insert('vg_message', Array) #3 /Users/yuichi/dev/VOYAGE_GROUP/vg-1day-2015-6-23/yopida/web-server/src/My1DayServer/Application.php(163): My1DayServer\Repository\MessageRepository->createMessage(Array) #4 /Users/yuichi/dev/VOYAGE_GROUP/vg-1day-2015-6-23/yopida/web-server/app.php(31): My1DayServer\Application->createMessage('', NULL, '/9j/4AAQSkZJRgA...', NULL) #5 [internal function]: {closure}(Object(Symfony\Component\HttpFoundation\Request)) #6 /Users/yuichi/dev/VOYAGE_GROUP/vg-1day-2015-6-23/yopida/web-server/vendor/symfony/http-kernel/Symfony/Component/HttpKernel/HttpKernel.php(145): call_user_func_array(Object(Closure), Array) #7 /Users/yuichi/dev/VOYAGE_GROUP/vg-1day-2015-6-23/yopida/web-server/vendor/symfony/http-kernel/Symfony/Component/HttpKernel/HttpKernel.php(66): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #8 /Users/yuichi/dev/VOYAGE_GROUP/vg-1day-2015-6-23/yopida/web-server/vendor/silex/silex/src/Silex/Application.php(547): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #9 /Users/yuichi/dev/VOYAGE_GROUP/vg-1day-2015-6-23/yopida/web-server/vendor/silex/silex/src/Silex/Application.php(524): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #10 /Users/yuichi/dev/VOYAGE_GROUP/vg-1day-2015-6-23/yopida/web-server/web/index.php(12): Silex\Application->run() #11 {main}  Next exception 'Doctrine\DBAL\Exception\InvalidFieldNameException' with message 'An exception occurred while executing 'INSERT INTO vg_message (username, body, icon, count, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?)' with params ["", null, "\/9j\/4AAQSkZJRgABAQAAAQABAAD\/\/gA7Q1JFQVRPUjogZ2QtanBlZyB2MS4wICh1c2luZyBJSkcgSlBFRyB2ODApLCBxdWFsaXR5ID0gOTAK\/9sAQwADAgIDAgIDAwMDBAMDBAUIBQUEBAUKBwcGCAwKDAwLCgsLDQ4SEA0OEQ4LCxAWEBETFBUVFQwPFxgWFBgSFBUU\/9sAQwEDBAQFBAUJBQUJFA0LDRQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQU\/8AAEQgAlgCWAwEiAAIRAQMRAf\/EAB8AAAEFAQEBAQEBAAAAAAAAAAABAgMEBQYHCAkKC\/\/EALUQAAIBAwMCBAMFBQQEAAABfQECAwAEEQUSITFBBhNRYQcicRQygZGhCCNCscEVUtHwJDNicoIJChYXGBkaJSYnKCkqNDU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6g4SFhoeIiYqSk5SVlpeYmZqio6Slpqeoqaqys7S1tre4ubrCw8TFxsfIycrS09TV1tfY2drh4uPk5ebn6Onq8fLz9PX29\/j5+v\/EAB8BAAMBAQEBAQEBAQEAAAAAAAABAgMEBQYHCAkKC\/\/EALURAAIBAgQEAwQHBQQEAAECdwABAgMRBAUhMQYSQVEHYXETIjKBCBRCkaGxwQkjM1LwFWJy0QoWJDThJfEXGBkaJicoKSo1Njc4OTpDREVGR0hJSlNUVVZXWFlaY2RlZmdoaWpzdHV2d3h5eoKDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uLj5OXm5+jp6vLz9PX29\/j5+v\/aAAwDAQACEQMRAD8A+y6KKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigCK5ma3tpZUjaZ0QsI16sQCQB7npXO6RqWryeKWtNQMcUT2RuFtogCIz5gUAtjJOAc4OOeldPXO\/81D\/7hf8A7WoAf4mur5bzSrOxu\/scl1I4aXy1fhVz0P8A9apdP0vV7a7SS61v7ZAud0P2RE3ZBA5ByMHB\/Cna5oFtrt1aGeeSJoAzCOJwpYMADk9ccY49TWPeaRD4T1TSptMaSGK5uVtprYyFlYMD82CScjGfy98gFua91TW9Wu7bTrpLC1tCI3uGiEjO5GSADwAOh\/zizoOpXhvrvTNRKSXduFkWaNdolQ9DjsQeD2\/nUPhD5LjXo2\/1g1GRiO+CAR+gNEX7z4gTleRHpyo+P7xkyM\/hQBsalqdtpNt593IYodwUvtLAE8DOAcD3PFLf6la6ZZvdXMoigUAlyCRycDAGSc57U+6t4ru1lgnRXhdSrg9CCOa8\/wBAkGpaxZ2F3O82mWrSNYs64FwVOBk9DtGcfT8KAPRIpBNErrna4DDIIOCM8g4I+h5rC8UahqlrBONPiSJIbdp5LuXBAwCdqjuxx1PABHrW\/Wd4k\/5F7VP+vWX\/ANANAEmiXEl3o1hPK2+WW3jd2wBklQScDgcntXOaPHruu2ZvE137NG8jhY\/scb4AYgcnGelb3h0hfDumEnAFpESScADYKyLb4faULVVeSe5IBMcpmIKZJOVAwByc9DyaAL2o6hc+HdAEk0o1G+LCNGMYQSOzEKCAcAAHsece9Z16\/iHQrQ6jPfQ38UWGntVgCBVyM7WHJI9\/T8Kynu55dFsluZTOLDWlhadjkuikgEn8QM+1dZ4pdY\/DeplzgfZnAz6lSB+pFAGlDKs8KSoco6hlPsRkGn1R0KNotD05HBDrbxgg+oUA1eoAKKKKACiiigCtqEFxc2ckdrc\/Y5zjbP5Yk24IJ4PByAR+Oa53\/hE9X\/tH7d\/wkP8ApXk+R5n2JPuZ3YxnHXnOM+9dXRQBiaj4be\/FnOL6SDU7eMJ9riUDfwM5TpgnJx0GaZY+GZVv4r3UtRk1OeEHyg0YjRCRgkKOM+\/\/ANat6igDD1Hw3LNqD32n6hJptzKoWYrGHWQDgEqeMgcZqzouhpo6zu0z3d3cMGmuJMbnIGAMDoAOgrTooAz9b02XVtOktIrn7IJCBI6ruJXuByME9M88Z4qvqnhmC90uC0gY2b2xVreZBkxkdDjIznvzz1rYooAZErrEgkYO4ADMBgMcckDJx9MmsTWdD1PVHuUi1r7NZTLsNv8AZVfAK4I3Eg88n2z7VvUUAYei6De6dF9nu9TGoWSweQtubdUAAAAOQSTgAjB65qrF4TvrOI21lrs9tY8gQmJXZAewcnI9sV01FAGSnhmyTQjpWwm2YEMScsSTncT655\/D04rPHhG5ufLhv9YmvrGMgi3MarvwcgOwOWHA6101FAABgYHAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigD\/9k=", null, "2015-06-23 06:39:27", "2015-06-23 06:39:27"]:  SQLSTATE[HY000]: General error: 1 table vg_message has no column named count' in /Users/yuichi/dev/VOYAGE_GROUP/vg-1day-2015-6-23/yopida/web-server/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractSQLiteDriver.php:66 Stack trace: #0 /Users/yuichi/dev/VOYAGE_GROUP/vg-1day-2015-6-23/yopida/web-server/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(116): Doctrine\DBAL\Driver\AbstractSQLiteDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException)) #1 /Users/yuichi/dev/VOYAGE_GROUP/vg-1day-2015-6-23/yopida/web-server/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(996): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOSqlite\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'INSERT INTO vg_...', Array) #2 /Users/yuichi/dev/VOYAGE_GROUP/vg-1day-2015-6-23/yopida/web-server/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(696): Doctrine\DBAL\Connection->executeUpdate('INSERT INTO vg_...', Array, Array) #3 /Users/yuichi/dev/VOYAGE_GROUP/vg-1day-2015-6-23/yopida/web-server/src/My1DayServer/Repository/MessageRepository.php(54): Doctrine\DBAL\Connection->insert('vg_message', Array) #4 /Users/yuichi/dev/VOYAGE_GROUP/vg-1day-2015-6-23/yopida/web-server/src/My1DayServer/Application.php(163): My1DayServer\Repository\MessageRepository->createMessage(Array) #5 /Users/yuichi/dev/VOYAGE_GROUP/vg-1day-2015-6-23/yopida/web-server/app.php(31): My1DayServer\Application->createMessage('', NULL, '/9j/4AAQSkZJRgA...', NULL) #6 [internal function]: {closure}(Object(Symfony\Component\HttpFoundation\Request)) #7 /Users/yuichi/dev/VOYAGE_GROUP/vg-1day-2015-6-23/yopida/web-server/vendor/symfony/http-kernel/Symfony/Component/HttpKernel/HttpKernel.php(145): call_user_func_array(Object(Closure), Array) #8 /Users/yuichi/dev/VOYAGE_GROUP/vg-1day-2015-6-23/yopida/web-server/vendor/symfony/http-kernel/Symfony/Component/HttpKernel/HttpKernel.php(66): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #9 /Users/yuichi/dev/VOYAGE_GROUP/vg-1day-2015-6-23/yopida/web-server/vendor/silex/silex/src/Silex/Application.php(547): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #10 /Users/yuichi/dev/VOYAGE_GROUP/vg-1day-2015-6-23/yopida/web-server/vendor/silex/silex/src/Silex/Application.php(524): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #11 /Users/yuichi/dev/VOYAGE_GROUP/vg-1day-2015-6-23/yopida/web-server/web/index.php(12): Silex\Application->run() #12 {main} [] []
[2015-06-23 06:40:26] api.ERROR: exception 'Symfony\Component\Debug\Exception\ContextErrorException' with message 'Warning: Missing argument 4 for My1DayServer\Application::createMessage(), called in /Users/yuichi/dev/VOYAGE_GROUP/vg-1day-2015-6-23/yopida/web-server/app.php on line 31 and defined' in /Users/yuichi/dev/VOYAGE_GROUP/vg-1day-2015-6-23/yopida/web-server/src/My1DayServer/Application.php:156 Stack trace: #0 /Users/yuichi/dev/VOYAGE_GROUP/vg-1day-2015-6-23/yopida/web-server/src/My1DayServer/Application.php(156): Symfony\Component\Debug\ErrorHandler->handleError(2, 'Missing argumen...', '/Users/yuichi/d...', 156, Array) #1 /Users/yuichi/dev/VOYAGE_GROUP/vg-1day-2015-6-23/yopida/web-server/app.php(31): My1DayServer\Application->createMessage('', 'ffffff', '/9j/4AAQSkZJRgA...') #2 [internal function]: {closure}(Object(Symfony\Component\HttpFoundation\Request)) #3 /Users/yuichi/dev/VOYAGE_GROUP/vg-1day-2015-6-23/yopida/web-server/vendor/symfony/http-kernel/Symfony/Component/HttpKernel/HttpKernel.php(145): call_user_func_array(Object(Closure), Array) #4 /Users/yuichi/dev/VOYAGE_GROUP/vg-1day-2015-6-23/yopida/web-server/vendor/symfony/http-kernel/Symfony/Component/HttpKernel/HttpKernel.php(66): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /Users/yuichi/dev/VOYAGE_GROUP/vg-1day-2015-6-23/yopida/web-server/vendor/silex/silex/src/Silex/Application.php(547): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /Users/yuichi/dev/VOYAGE_GROUP/vg-1day-2015-6-23/yopida/web-server/vendor/silex/silex/src/Silex/Application.php(524): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #7 /Users/yuichi/dev/VOYAGE_GROUP/vg-1day-2015-6-23/yopida/web-server/web/index.php(12): Silex\Application->run() #8 {main} [] []
[2015-06-23 06:41:35] api.ERROR: exception 'Symfony\Component\Debug\Exception\ContextErrorException' with message 'Warning: Missing argument 4 for My1DayServer\Application::createMessage(), called in /Users/yuichi/dev/VOYAGE_GROUP/vg-1day-2015-6-23/yopida/web-server/app.php on line 31 and defined' in /Users/yuichi/dev/VOYAGE_GROUP/vg-1day-2015-6-23/yopida/web-server/src/My1DayServer/Application.php:156 Stack trace: #0 /Users/yuichi/dev/VOYAGE_GROUP/vg-1day-2015-6-23/yopida/web-server/src/My1DayServer/Application.php(156): Symfony\Component\Debug\ErrorHandler->handleError(2, 'Missing argumen...', '/Users/yuichi/d...', 156, Array) #1 /Users/yuichi/dev/VOYAGE_GROUP/vg-1day-2015-6-23/yopida/web-server/app.php(31): My1DayServer\Application->createMessage('', 'dddd', '/9j/4AAQSkZJRgA...') #2 [internal function]: {closure}(Object(Symfony\Component\HttpFoundation\Request)) #3 /Users/yuichi/dev/VOYAGE_GROUP/vg-1day-2015-6-23/yopida/web-server/vendor/symfony/http-kernel/Symfony/Component/HttpKernel/HttpKernel.php(145): call_user_func_array(Object(Closure), Array) #4 /Users/yuichi/dev/VOYAGE_GROUP/vg-1day-2015-6-23/yopida/web-server/vendor/symfony/http-kernel/Symfony/Component/HttpKernel/HttpKernel.php(66): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /Users/yuichi/dev/VOYAGE_GROUP/vg-1day-2015-6-23/yopida/web-server/vendor/silex/silex/src/Silex/Application.php(547): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /Users/yuichi/dev/VOYAGE_GROUP/vg-1day-2015-6-23/yopida/web-server/vendor/silex/silex/src/Silex/Application.php(524): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #7 /Users/yuichi/dev/VOYAGE_GROUP/vg-1day-2015-6-23/yopida/web-server/web/index.php(12): Silex\Application->run() #8 {main} [] []
[2015-06-23 06:43:41] api.ERROR: exception 'Symfony\Component\Debug\Exception\ContextErrorException' with message 'Warning: Missing argument 4 for My1DayServer\Application::createMessage(), called in /Users/yuichi/dev/VOYAGE_GROUP/vg-1day-2015-6-23/yopida/web-server/app.php on line 31 and defined' in /Users/yuichi/dev/VOYAGE_GROUP/vg-1day-2015-6-23/yopida/web-server/src/My1DayServer/Application.php:156 Stack trace: #0 /Users/yuichi/dev/VOYAGE_GROUP/vg-1day-2015-6-23/yopida/web-server/src/My1DayServer/Application.php(156): Symfony\Component\Debug\ErrorHandler->handleError(2, 'Missing argumen...', '/Users/yuichi/d...', 156, Array) #1 /Users/yuichi/dev/VOYAGE_GROUP/vg-1day-2015-6-23/yopida/web-server/app.php(31): My1DayServer\Application->createMessage('', 'ddddd', '/9j/4AAQSkZJRgA...') #2 [internal function]: {closure}(Object(Symfony\Component\HttpFoundation\Request)) #3 /Users/yuichi/dev/VOYAGE_GROUP/vg-1day-2015-6-23/yopida/web-server/vendor/symfony/http-kernel/Symfony/Component/HttpKernel/HttpKernel.php(145): call_user_func_array(Object(Closure), Array) #4 /Users/yuichi/dev/VOYAGE_GROUP/vg-1day-2015-6-23/yopida/web-server/vendor/symfony/http-kernel/Symfony/Component/HttpKernel/HttpKernel.php(66): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /Users/yuichi/dev/VOYAGE_GROUP/vg-1day-2015-6-23/yopida/web-server/vendor/silex/silex/src/Silex/Application.php(547): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /Users/yuichi/dev/VOYAGE_GROUP/vg-1day-2015-6-23/yopida/web-server/vendor/silex/silex/src/Silex/Application.php(524): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #7 /Users/yuichi/dev/VOYAGE_GROUP/vg-1day-2015-6-23/yopida/web-server/web/index.php(12): Silex\Application->run() #8 {main} [] []
